# .streamlit/secrets.toml

[connections.supabase]
SUPABASE_URL = "https://glkczgaethcpkqerbfrj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdsa2N6Z2FldGhjcGtxZXJiZnJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDk1Njc5NTUsImV4cCI6MjAyNTE0Mzk1NX0.551nYz95SJW7ygURNW_SMzSfGefp9lxpPFgIZSib9pE"
